name: cebms

services:
  postgres:
    image: postgres:16
    container_name: cebms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cebms_user
      POSTGRES_PASSWORD: cebms_pw
      POSTGRES_DB: cebms
    ports:
      - "5432:5432"
    volumes:
      - cebms_legacy_pgdata:/var/lib/postgresql/data

volumes:
  cebms_legacy_pgdata:
    external: true
    name: cebms_cebms_pgdata